-- Create the 'analyses' table
CREATE TABLE
  analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone ('utc'::TEXT, NOW()) NOT NULL,
    user_id UUID,
    text_input TEXT,
    url_input TEXT,
    summary JSONB,
    analysis_details JSONB,
    sources JSONB
  );

-- Enable Row Level Security (RLS) on the 'analyses' table
ALTER TABLE analyses ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow anonymous inserts into the 'analyses' table
-- This allows the public 'anon' key to insert data, which is what the Next.js server action uses.
CREATE POLICY "Allow inserts for anon users" ON analyses
  FOR INSERT
  TO anon
  WITH CHECK (TRUE);
